# Generated by Django 6.1.1 on 2026-09-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_follow_table(apps, schema_editor):
    quote = schema_editor.connection.ops.quote_name
    schema_editor.execute(
        f"ALTER TABLE {quote('palshare_follow')} "
        f"RENAME TO {quote('connections_follow')}"
    )


def reverse_rename_follow_table(apps, schema_editor):
    quote = schema_editor.connection.ops.quote_name
    schema_editor.execute(
        f"ALTER TABLE {quote('connections_follow')} "
        f"RENAME TO {quote('palshare_follow')}"
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("palshare", "0004_alter_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Follow",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "follower",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="following",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "following",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="followers",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "connections_follow",
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("follower", "following"),
                                name="one_follow_per_pair",
                            ),
                            models.CheckConstraint(
                                condition=~models.Q(
                                    follower=models.F("following")
                                ),
                                name="no_self_follow",
                            ),
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    rename_follow_table,
                    reverse_rename_follow_table,
                ),
            ],
        ),
    ]
