# Generated by Django 6.1.1 on 2026-09-27 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "palshare_like" RENAME TO "interactions_like";\nALTER TABLE "palshare_save" RENAME TO "interactions_save";\nALTER TABLE "palshare_share" RENAME TO "interactions_share";\nALTER TABLE "palshare_reaction" RENAME TO "interactions_reaction";\nALTER TABLE "palshare_commentlike" RENAME TO "interactions_commentlike";',
                    reverse_sql='ALTER TABLE "interactions_commentlike" RENAME TO "palshare_commentlike";\nALTER TABLE "interactions_reaction" RENAME TO "palshare_reaction";\nALTER TABLE "interactions_share" RENAME TO "palshare_share";\nALTER TABLE "interactions_save" RENAME TO "palshare_save";\nALTER TABLE "interactions_like" RENAME TO "palshare_like";',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CommentLike',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.comment')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('user', 'comment'), name='one_comment_like_per_user')],
                    },
                ),
                migrations.CreateModel(
                    name='Like',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='one_like_per_user')],
                    },
                ),
                migrations.CreateModel(
                    name='Reaction',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('emoji', models.CharField(choices=[('👍', 'Thumbs up'), ('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Surprise'), ('🎉', 'Celebrate')], max_length=4)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='one_reaction_per_user')],
                    },
                ),
                migrations.CreateModel(
                    name='Save',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='posts.post')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='one_save_per_user')],
                    },
                ),
                migrations.CreateModel(
                    name='Share',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='one_share_per_user')],
                    },
                ),
            ],
        ),
    ]
