# Generated by Django 6.1.1 on 2026-09-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_messaging_tables(apps, schema_editor):
    quote = schema_editor.connection.ops.quote_name

    table_renames = [
        ("palshare_conversation", "messaging_conversation"),
        (
            "palshare_conversation_participants",
            "messaging_conversation_participants",
        ),
        ("palshare_message", "messaging_message"),
    ]

    for old_name, new_name in table_renames:
        schema_editor.execute(
            f"ALTER TABLE {quote(old_name)} "
            f"RENAME TO {quote(new_name)}"
        )


def reverse_rename_messaging_tables(apps, schema_editor):
    quote = schema_editor.connection.ops.quote_name

    table_renames = [
        ("messaging_message", "palshare_message"),
        (
            "messaging_conversation_participants",
            "palshare_conversation_participants",
        ),
        ("messaging_conversation", "palshare_conversation"),
    ]

    for old_name, new_name in table_renames:
        schema_editor.execute(
            f"ALTER TABLE {quote(old_name)} "
            f"RENAME TO {quote(new_name)}"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("palshare", "0004_alter_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Conversation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True),
                        ),
                        (
                            "participants",
                            models.ManyToManyField(
                                related_name="conversations",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "messaging_conversation",
                        "ordering": ["-updated_at"],
                    },
                ),
                migrations.CreateModel(
                    name="Message",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("text", models.TextField()),
                        (
                            "sent_at",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "read_at",
                            models.DateTimeField(
                                blank=True,
                                null=True,
                            ),
                        ),
                        (
                            "edited_at",
                            models.DateTimeField(
                                blank=True,
                                null=True,
                            ),
                        ),
                        (
                            "deleted_at",
                            models.DateTimeField(
                                blank=True,
                                null=True,
                            ),
                        ),
                        (
                            "conversation",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="messages",
                                to="messaging.conversation",
                            ),
                        ),
                        (
                            "sender",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="sent_messages",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "messaging_message",
                        "ordering": ["sent_at"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    rename_messaging_tables,
                    reverse_rename_messaging_tables,
                ),
            ],
        ),
    ]
