# Generated by Django 6.1.1 on 2026-09-24 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palshare', '0003_message_deleted_at_message_edited_at_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
