# Generated by Django 6.1.1 on 2026-09-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("palshare", "0004_alter_profile_user"),
        ("connections", "0001_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Old PalShare model states are removed here only.
                # Their database tables are preserved because the
                # database_operations list is intentionally empty.

                migrations.DeleteModel(
                    name="CommentLike",
                ),
                migrations.DeleteModel(
                    name="Like",
                ),
                migrations.DeleteModel(
                    name="Reaction",
                ),
                migrations.DeleteModel(
                    name="Save",
                ),
                migrations.DeleteModel(
                    name="Share",
                ),
                migrations.DeleteModel(
                    name="Media",
                ),
                migrations.DeleteModel(
                    name="Comment",
                ),
                migrations.DeleteModel(
                    name="Post",
                ),
                migrations.DeleteModel(
                    name="Message",
                ),
                migrations.DeleteModel(
                    name="Conversation",
                ),
                migrations.DeleteModel(
                    name="Follow",
                ),
                migrations.DeleteModel(
                    name="Profile",
                ),
            ],
            database_operations=[],
        ),
    ]
